---
- name: Deploy app with docker-compose
  hosts: staging
  remote_user: gxmzalx
  gather_facts: false
  become: true
  tasks:
  - name: Create the app dir
    file:
      path: /home/gxmzalx/p5
      state: directory
      owner: gxmzalx
      group: gxmzalx

  - name: Copy docker files
    copy:
      src: /var/lib/jenkins/workspace/P5/Practica_5
      dest: /home/gxmzalx/p5
      owner: gxmzalx
      group: gxmzalx

  - name: Up
    make:
      chdir: /home/gxmzalx/p5
      target: run

  - name: Install "secure-delete" package
      apt:
        name: secure-delete
        state: present
  - name: Secure deleting application files
    command: srm -vzr /home/gxmzalx/p5