version: "3.3"
services:
  test:
    build: .
    image: "gomzalo/practica_5_test:latest"
    container_name: p5p14_test
    ports:
      - "8081:5050"
    restart: on-failure

  production:
    build: .
    image: "gomzalo/practica_5_production:latest"
    container_name: p5p14_prod
    ports:
      - "8082:5050"
    restart: on-failure