### SERVER LOGIN ###

###
GET http://localhost:4004/getuser HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVwb2t1biIsInBhc3MiOiJheW1pbWFkcmUiLCJyb2wiOjEsImlhdCI6MTY0Mzc3Njg2MX0.HW_8Gm9Sg7ImyCXwm3c2mgsV5GnidKeqZD-iuxeWKGI

###
POST http://localhost:3003/login HTTP/1.1
content-type: application/json
{
    "username" : "Tepokun",
    "password" : "aymimadre",
    "rol" : 2
}

###
DELETE http://localhost:3003/logout HTTP/1.1
content-type: application/json
{
    "token" : ""
}

###
POST http://localhost:3003/token HTTP/1.1
content-type: application/json
{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiVGVwb2t1biIsImlhdCI6MTY0Mzc3NDYwMX0.a7uqRCaQDxusD60ERypYkXjDhdcITvAU1WKye0kPPF4"
}