apiVersion: v1
kind: Service
metadata:
    labels:
        app: back
    name: back-svc
spec:
    ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
        app: back
    type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
    labels:
        app: client
    name: client-svc
spec:
    ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
        app: client
    type: LoadBalancer